sudo: false
dist: xenial

services:
  - docker

env:
  DRAFT_DIR: /home/idci/draft
  CONTAINER: /tmp/docker.container

before_install:
  - docker --version
  - docker pull martinthomson/i-d-template

script:
  - docker run -d -v "$PWD:$DRAFT_DIR" martinthomson/i-d-template sleep 300 >"$CONTAINER"
  - docker exec $(cat "$CONTAINER") -w "$DRAFT_DIR" make 'CLONE_ARGS=--reference ~/git-reference'
  - if [ "${TRAVIS_TAG#draft-}" == "${TRAVIS_TAG}" ]; then
      docker exec $(cat "$CONTAINER") -w "$DRAFT_DIR" make gh-pages
    fi
  - docker exec $(cat "$CONTAINER") -w "$DRAFT_DIR" make issues
  - docker kill $(cat "$CONTAINER") && rm "$CONTAINER"

after_failure:
  - docker kill $(cat "$CONTAINER") && rm "$CONTAINER"

deploy:
  provider: script
  script: docker run -d -v "$PWD:$DRAFT_DIR" -w "$DRAFT_DIR" make upload
  skip_cleanup: true
  on:
    tags: true
