sudo: required
dist: xenial

services:
  - docker

env:
  DRAFT_DIR: /home/idci/draft
  CLONE_ARGS: --reference ~/git-reference

before_install:
  - docker --version
  - docker pull martinthomson/i-d-template

script:
  - docker run -d -v "$PWD:/tmp/draft" --tmpfs "$DRAFT_DIR" --name idci
      martinthomson/i-d-template sleep 300
  - docker exec idci cp -R /tmp/draft "$DRAFT_DIR"
  - docker exec -w "$DRAFT_DIR" -e CI=true -e CLONE_ARGS
      -e TRAVIS_REPO_SLUG -e TRAVIS_BRANCH -e TRAVIS_TAG -e TRAVIS_PULL_REQUEST
      idci make ghpages

deploy:
  provider: script
  script:
    - docker exec -w "$DRAFT_DIR" -e CI=true -e CLONE_ARGS
        -e TRAVIS_REPO_SLUG -e TRAVIS_BRANCH -e TRAVIS_TAG -e TRAVIS_PULL_REQUEST
        idci make upload
  skip_cleanup: true
  on:
    tags: true

after_script:
  - docker container rm -f idci
